# Changes here will be overwritten by Copier
AnswerStrategy: recommended
Authors: Alberto Mengali <a.mengali@gmail.com>
CodeOfConductContact: a.mengali@gmail.com
ConfigIndentation: 2
JuliaIndentation: 4
JuliaMinVersion: '1.10'
License: MIT
LicenseCopyrightHolders: Alberto Mengali
MarkdownIndentation: 2
PackageName: ExtendedLocalCoverage
PackageOwner: disberd
PackageUUID: eb248270-a497-541c-8f75-6bb2aa2715dc
_commit: v0.14.1
_src_path: https://github.com/JuliaBesties/BestieTemplate.jl
